# Generated by Django 3.1.2 on 2022-06-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_auto_20201128_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='anios_cotizados',
            field=models.PositiveIntegerField(default=0, max_length=100, verbose_name='Años cotizados'),
            preserve_default=False,
        ),
    ]
