# Generated by Django 3.1.2 on 2022-06-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_userprofile_anios_cotizados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='anios_cotizados',
            field=models.PositiveIntegerField(null=True, verbose_name='Años cotizados'),
        ),
    ]
