# Generated by Django 3.1.2 on 2022-06-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_user_pageadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pageadmin',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pageadmin',
            field=models.BooleanField(default=False),
        ),
    ]
