# Generated by Django 4.0.4 on 2022-06-03 00:55

from django.db import migrations, models
import empleados.models
import empleados.validators


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='curriculum',
            field=models.FileField(blank=True, null=True, upload_to=empleados.models.file_upload_location, validators=[empleados.validators.validate_file_extension, empleados.validators.validate_file_size], verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=empleados.models.image_upload_location, validators=[empleados.validators.validate_image_extension, empleados.validators.validate_file_size], verbose_name='Foto de perfil'),
        ),
        migrations.DeleteModel(
            name='HistoricalUser',
        ),
    ]
